<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer PO _</name>
   <tag></tag>
   <elementGuidId>a5dbb9b3-2b1b-42b1-9818-04ec0161288f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerPoNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'CustomerPoNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f437f34-5447-47ff-9c26-7a52fe2e32d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-custpo</value>
      <webElementGuid>f66f9549-e172-415c-b74a-1c6bb239b35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e1272d38-67e7-481b-85e6-9eccf480b489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>98c76bde-716c-42bf-b0ae-2fc1670b10dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1a004df-ae77-4fc8-9b7d-494eec306912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>PO number is 22 character max.</value>
      <webElementGuid>6f9176df-0dff-4ce4-ba65-8f406d27314f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>719c8d28-9e7f-49b5-abba-440fabc9bb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please provide a valid PO Number.</value>
      <webElementGuid>619b6430-ce49-4d69-a76b-da22992d962c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPoNumber</value>
      <webElementGuid>e70b6722-7b6f-4c2e-8912-7c1934c76fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>1ab058fd-36af-4b9f-be26-5f993650908a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerPoNumber</value>
      <webElementGuid>786f6f55-01bc-4d8a-8673-9c7f5681fd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer PO #_</value>
      <webElementGuid>490ff33b-4c88-46f5-906f-a722d6523da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2128cc7d0c3fbb23edbdb942e3141ae6</value>
      <webElementGuid>0bd315ca-614c-4f73-b848-b8101004d802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'CustomerPoNumber']</value>
      <webElementGuid>276dfc35-09c3-482a-8129-a92948c3de75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'CustomerPoNumber']</value>
      <webElementGuid>aaa1eaac-6c82-4070-a76d-ba8a4025289c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CustomerPoNumber' and @name = 'CustomerPoNumber' and (text() = 'Customer PO #_' or . = 'Customer PO #_')]</value>
      <webElementGuid>37ee1c66-d75f-4a13-88b0-f1a9dd8f3d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
