<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_selectedAccount</name>
   <tag></tag>
   <elementGuidId>7f1ed0a9-3112-42ac-9fa6-d7153483e2df</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.details:nth-child(2) .links</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@@text = '11283290']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7f9beaf-edfc-4ed4-bb8a-9af991c4c6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedAccount</value>
      <webElementGuid>71456ccc-d02a-4944-a31a-412a5a097ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>links</value>
      <webElementGuid>0dd2011a-f86b-4203-8892-0030371df461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>888117</value>
      <webElementGuid>9c3a1025-02ee-409d-ae79-02667c76afe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>account-select-1</value>
      <webElementGuid>e65b7c7c-b91c-46f2-880e-e17654ebf227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-target</name>
      <type>Main</type>
      <value>7fda1210-f170-49bd-a481-0ac2f036e412</value>
      <webElementGuid>d0578710-5c67-48b8-92cc-71ce24a76d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>selectedAccount</value>
      <webElementGuid>d37a308f-1bf4-4db9-b2d9-43b8112b208c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>11283290</value>
      <webElementGuid>302b59c9-f2aa-46eb-818a-05c0c687cf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c9277bddf195219914d78a700ee05685</value>
      <webElementGuid>828e1dc3-a896-4889-ae84-96f51151b353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      <webElementGuid>9a106303-70c5-4c6c-b97d-547129a575f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      <webElementGuid>a7ca69ed-6749-4404-9823-02344459470b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'selectedAccount' and (text() = 'selectedAccount' or . = 'selectedAccount')]</value>
      <webElementGuid>f6bb7614-8a7b-4b76-9949-cb350c458674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
