<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_level1</name>
   <tag></tag>
   <elementGuidId>4d84be5b-34ab-4ac9-8a25-d911d6d2834c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-e2e-testing-id=&quot;product-menu&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-e2e-testing-id = 'product-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Products &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d37612bf-fc5e-4269-a1a7-93fef48cd396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle</value>
      <webElementGuid>8b6f02bb-d1d4-444d-b823-a80b1c67c1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>97eac45f-4925-43d5-95bd-9b79efd9f0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>level1</value>
      <webElementGuid>b0bd3784-fc47-46ce-bacd-91f0c7e5346d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a027b4b2-c47f-42ec-b0ed-ee3649b4f1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>product-menu</value>
      <webElementGuid>6d893e13-3f97-4bde-9d28-8f4707643de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f58993f6-99c1-4da6-b5bf-975280bb3a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c6bdfb7-05b3-49e6-bfd7-fb5132b59d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84e79e7c-810a-431d-b356-e14de2597eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>level1</value>
      <webElementGuid>598fd2d4-69d2-45fc-944c-599455582417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>PRODUCTS</value>
      <webElementGuid>93180db7-2300-4dd1-a90e-8957dcb921e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d754c5b0b30fbb6dbdc69359d2a3ab7b</value>
      <webElementGuid>83e9f438-215c-4940-a16e-17cadce186de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-e2e-testing-id = 'product-menu']</value>
      <webElementGuid>c00e5218-54e2-4c6b-92a6-44d238db9c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-e2e-testing-id = 'product-menu']</value>
      <webElementGuid>94b1080b-9255-495d-9a39-46204b836f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'level1' and (text() = 'level1' or . = 'level1')]</value>
      <webElementGuid>b64dcec6-085f-414b-8f44-bacff327b3ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
