<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkout-btn</name>
   <tag></tag>
   <elementGuidId>db8ebc76-f932-4192-8314-f54158d9cf28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'checkout-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63b9059e-d65b-491c-bac3-e15844c64f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { disabled: !hasShippingMethod() || isDisable() || checkoutDisable() || hasInvalidDnr() }</value>
      <webElementGuid>3470c4fc-8076-4202-aba9-112377481456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>bc87be04-3e68-4f05-83f5-43d7bbe2e265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>28cf684a-03a7-4515-b474-552504ba51bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf696000-3aa0-4dcb-89b5-67105f503274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cartService.checkout()</value>
      <webElementGuid>7116a42a-9cf3-4107-aa84-d43a5d38b7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn checkout</value>
      <webElementGuid>3476f930-88fb-4b4a-9bfd-9c07e487c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>476a30c5-8641-49dd-8b50-8dc8d3277840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>71749f66-868a-43d7-bd98-b4d0869ef4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1953c70763ee508726ffb0f720002ac8</value>
      <webElementGuid>c1219fc0-a871-4786-bfa7-fed83335aab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'checkout-btn']</value>
      <webElementGuid>533ff0fe-643e-4bac-a816-adc2a421b174</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'checkout-btn']</value>
      <webElementGuid>b7fc9cdc-0cb8-40ba-96fb-5a399deec6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkout-btn' and @type = 'button' and (text() = 'checkout-btn' or . = 'checkout-btn')]</value>
      <webElementGuid>90fd8532-6101-4ab0-9d13-83e6c9236eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
