<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>bc0c07d2-1f27-46aa-b8cc-36735d3958aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='page-content']/header/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-4.account > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Change&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81fd91b8-fc03-405a-bc6e-14e0e28dc44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/account/select</value>
      <webElementGuid>7d7ba935-1c74-4d8c-8621-ce366e871b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Change</value>
      <webElementGuid>2476db73-93cb-4c9d-907b-ce4280784019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-content&quot;)/header[@class=&quot;loggedin&quot;]/div[@class=&quot;quicklinks&quot;]/div[@class=&quot;container d-flex&quot;]/div[@class=&quot;col-sm-4 account&quot;]/a[1]</value>
      <webElementGuid>5188b44c-a432-4028-9342-b20952f1993a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='page-content']/header/div/div/div[2]/a</value>
      <webElementGuid>e6fb372c-b71c-473f-8f78-4009d77d5d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Change')]</value>
      <webElementGuid>34a00ab9-0cca-45fb-b93b-0d6be271c9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(48314070-DEFAULT-GOSSELIN ELECTRIQUE INC)'])[1]/following::a[1]</value>
      <webElementGuid>5ff7589f-c30f-465f-b4c7-fa7b29c8394c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tejal.patel_extsonepar.ca'])[1]/following::a[1]</value>
      <webElementGuid>95974b0d-83d7-40d7-bec9-9661bb7ad756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lumen Exhibition'])[1]/preceding::a[1]</value>
      <webElementGuid>3899f3e3-d7e7-429b-b971-298e250f2945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalogues'])[1]/preceding::a[2]</value>
      <webElementGuid>b9c1307d-c244-4c9d-ab60-fe5aa6024ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change']/parent::*</value>
      <webElementGuid>33d76bec-579e-4b23-900a-49718458bac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en/account/select')]</value>
      <webElementGuid>33bac4ff-881b-4547-82cc-211e4207b054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>cccc09a8-c8bc-49d9-a505-fa2714186256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/account/select' and (text() = ' Change' or . = ' Change')]</value>
      <webElementGuid>37c1432f-d517-4b11-906a-329c3e026c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
