<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>87bcde81-23a3-42fb-99b3-5115a9938a34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.account [href=&quot;\/en\/account\/select&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' account ')]//*[@href = '/en/account/select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Change&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a545f1c4-f9fe-4059-97e0-49ff8b3b04ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/account/select</value>
      <webElementGuid>60973f79-a499-4ff3-9cdb-137c34f602fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>9fe84e93-0130-497c-90ab-69ad6ca0d98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>aea69ae0-5106-4ba4-b163-787d21bbf940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ab8d77fb4616267bfdc2778162b72957</value>
      <webElementGuid>8cf0be80-4d2d-479b-b56f-4793c57a500b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' account ')]//*[@href = '/en/account/select']</value>
      <webElementGuid>34a99362-46de-4f36-bdf4-cb212add8831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' account ')]//*[@href = '/en/account/select']</value>
      <webElementGuid>cccc19eb-7b27-4b7f-9198-ffbd11aa084b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/account/select' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>7ac1a819-b99c-47ee-8950-54ba232f5a8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
