<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Submit Order</name>
   <tag></tag>
   <elementGuidId>88137677-a25b-42b0-8c2e-a69891926391</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#summary-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'summary-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0a65cda-5e65-4b2f-baee-a0f9e3da058e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-submit-btn</value>
      <webElementGuid>4584fc97-6906-4904-a1be-a89531a94a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>summary-submit</value>
      <webElementGuid>d394ed1b-cbd1-4d97-87d3-f875175cc11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn checkout</value>
      <webElementGuid>ca88691f-d413-4c60-b67d-4f3769dbef35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>16db9679-fb44-4f72-8033-f656216c1e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Submit Order</value>
      <webElementGuid>9dd61fac-776f-421b-8216-561abc88c011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit Order</value>
      <webElementGuid>a54c2f2b-d61b-4715-8b63-68cd23692382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Order</value>
      <webElementGuid>7e6ad3b6-2d34-43b7-bbb3-9f27a5b7e325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f40d63d09f027c8de71f2d746928b65e</value>
      <webElementGuid>b90bc0a7-f139-419d-8e13-86326ec82df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'summary-submit']</value>
      <webElementGuid>c30c853d-6fc7-4a66-a01d-c0783e869e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'summary-submit']</value>
      <webElementGuid>4cac6a26-16b8-4f52-822e-e623635b5894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'summary-submit' and @type = 'submit' and @alt = 'Submit Order' and (text() = 'Submit Order' or . = 'Submit Order')]</value>
      <webElementGuid>e215c86f-0692-4261-8ef1-3621ef3111d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
