<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer PO _</name>
   <tag></tag>
   <elementGuidId>15a716d9-a6ad-4778-ac1b-a69a964a0658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerPoNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'CustomerPoNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5606f891-0f32-4b6b-8234-e881adf000c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-custpo</value>
      <webElementGuid>3f43d96c-7770-47f2-ba28-af2f7cdcf64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6733f2dd-2c4c-4c09-9cad-24880b5ae678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>53ee9e06-e39f-4da3-8ea2-efd9341c9799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33bec45c-50e7-4990-8ccc-32148b2ea543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>PO number is 22 character max.</value>
      <webElementGuid>cceb0fae-7234-4a16-ac48-25999263bd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>de45afcc-2b5a-4808-8324-27e80aa6080e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please provide a valid PO Number.</value>
      <webElementGuid>1d78a274-40a2-4f92-8925-b5fd0aa9c0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPoNumber</value>
      <webElementGuid>0513da04-55f5-45e9-8989-2e83aad56375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>f8e4f08d-596b-4c97-908c-1540d9f67034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerPoNumber</value>
      <webElementGuid>eb866ceb-f725-4856-8bfc-693061e0792d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer PO #_</value>
      <webElementGuid>a619caaf-3236-4110-9621-8b6a5de4e3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2128cc7d0c3fbb23edbdb942e3141ae6</value>
      <webElementGuid>4c3e0821-bd88-4f4c-85b2-7f1def30f1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'CustomerPoNumber']</value>
      <webElementGuid>dfcd27b8-b51a-421c-93be-d0120edaa698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'CustomerPoNumber']</value>
      <webElementGuid>789b998e-3c3a-425c-9a65-89b06050379d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CustomerPoNumber' and @name = 'CustomerPoNumber' and (text() = 'Customer PO #_' or . = 'Customer PO #_')]</value>
      <webElementGuid>c640c9f8-7cdd-4e02-99da-b9066b69d247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
