<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FR_query</name>
   <tag></tag>
   <elementGuidId>e70b9778-5d5f-48da-874f-43af81f5a7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MenuContent_txtSearchField']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MenuContent_txtSearchField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Products Search or Product Code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f40795a-f434-48d1-ae92-9f009436a10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>e0e4b6e4-d931-420d-8f38-f2b1ffd86c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuContent_txtSearchField</value>
      <webElementGuid>53c29d19-6d7b-4fee-b56d-be5dce63655d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>search-bar</value>
      <webElementGuid>09b0c1e7-bb57-484b-8035-57768667443b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>35cb57a0-f805-4d67-8d68-c644e7c5595b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control typeahead data-hj-allow</value>
      <webElementGuid>daf14608-7390-488a-8542-0c87869b4a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d055f6fe-fe41-47e2-b1cb-8759cc720333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Products Search or Product Code</value>
      <webElementGuid>db5eac8f-85cf-434d-a8ae-289a4d2e9ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>a73aaec9-3bff-41e5-948a-2d2ae3671c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hx-post</name>
      <type>Main</type>
      <value>/en/search/typeahead</value>
      <webElementGuid>a95d87f1-ddc9-4a63-bd72-abf69e9b9bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hx-target</name>
      <type>Main</type>
      <value>.el-search-panel</value>
      <webElementGuid>abc8ab58-7400-4176-b470-e240dfa89aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hx-include</name>
      <type>Main</type>
      <value>[name=query]</value>
      <webElementGuid>76621608-fa3d-45b3-a627-acb9700cec76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hx-trigger</name>
      <type>Main</type>
      <value>keyup delay:250ms, click delay:250ms</value>
      <webElementGuid>6f73ed73-8d5f-42f9-8602-d225c6c7a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent_txtSearchField&quot;)</value>
      <webElementGuid>3ce898d0-4008-46a4-aab1-83b05d5a7f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MenuContent_txtSearchField']</value>
      <webElementGuid>d0457ee8-573d-4e6a-8d9c-3d6adcd6df51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SearchBar']/input</value>
      <webElementGuid>95673ac0-58e6-4508-864f-2b211a914803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>ac7b49b6-5917-42bc-afc0-0e801740da73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'query' and @id = 'MenuContent_txtSearchField' and @type = 'search' and @placeholder = 'Products Search or Product Code']</value>
      <webElementGuid>3e1016d8-8bc8-4d04-a14d-f62a38534537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
