<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_selectedAccount</name>
   <tag></tag>
   <elementGuidId>97c419bb-2aea-43c0-9c4d-ed95cb15e46b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.details:nth-child(23) .links</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 23)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;21341740&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>155a071e-3aee-452e-8fe6-cdf09194077d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectedAccount</value>
      <webElementGuid>daa24e43-5bd3-4d54-9957-10e1f548ba45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>links</value>
      <webElementGuid>ed835d76-c1da-4fd9-8a6e-fc7f4d44750e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>974883</value>
      <webElementGuid>cec6bf65-09aa-4b6f-89f0-dd9c74f83d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>account-select-22</value>
      <webElementGuid>728eb3e0-1039-4dc8-b9ce-3c797b35cb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-search-target</name>
      <type>Main</type>
      <value>47177924-f8c5-4f03-a27c-604e99748bd7</value>
      <webElementGuid>bbf13874-8a98-4180-81fa-0e7e7eaa4192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>selectedAccount</value>
      <webElementGuid>2e64160a-a816-46cb-ba16-cdfd5e88d9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>21341740</value>
      <webElementGuid>8a67f63a-9cdf-4c88-92f8-831c2d88f933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fd82d235bdfececd440287bf3dddc690</value>
      <webElementGuid>44ff980b-04b5-46c8-88d8-5c485460940b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 23)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      <webElementGuid>daeaeb78-3e99-424e-8e94-1deddd370e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' details ') and (position() = 23)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' links ')]</value>
      <webElementGuid>536743b3-7619-49de-9467-89aab0142edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'selectedAccount' and (text() = 'selectedAccount' or . = 'selectedAccount')]</value>
      <webElementGuid>ca506492-ba15-4784-8cda-8c2e293c34fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
