<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Submit Order</name>
   <tag></tag>
   <elementGuidId>00c08d79-8f7c-44d3-8a83-d650a0178756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#summary-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'summary-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>642b1d1b-51a9-4002-9358-0bce03265364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-submit-btn</value>
      <webElementGuid>150e53f4-077a-4fd4-b9bf-7159b893c989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>summary-submit</value>
      <webElementGuid>b31c4cab-d771-49b0-88ca-4bc105a5bc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn checkout</value>
      <webElementGuid>faea5b6c-637f-4187-8aab-5e1b88642ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c4399f7e-d470-4b06-91c6-62f3f0d4f540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Submit Order</value>
      <webElementGuid>2d366756-0d19-4306-9914-be21f2c7b6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit Order</value>
      <webElementGuid>626674dd-5c5f-450d-8b4c-276e7a854152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Order</value>
      <webElementGuid>2d043901-0280-482e-af71-6b33a92ba1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f40d63d09f027c8de71f2d746928b65e</value>
      <webElementGuid>bb48c627-708f-4e6d-8db1-0bb62d0bb65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'summary-submit']</value>
      <webElementGuid>333f7196-ccac-4f42-a319-308e131ee22f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'summary-submit']</value>
      <webElementGuid>d952e668-907f-48aa-91dd-330c2c1bcaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'summary-submit' and @type = 'submit' and @alt = 'Submit Order' and (text() = 'Submit Order' or . = 'Submit Order')]</value>
      <webElementGuid>e7756052-a23d-4263-a43c-74d666904534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
