<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer PO _</name>
   <tag></tag>
   <elementGuidId>0d0386d6-7db4-4a0a-bcfc-1db98c9ecf85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomerPoNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'CustomerPoNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3053677c-dde5-4c9e-bc92-61fa8b36813c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-custpo</value>
      <webElementGuid>9dd23db0-b9b9-4ada-95f0-0b5082ba688a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>03b3755d-7fac-42e5-b1e3-fd8a12e77db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0b8a15c7-d3fc-425f-a773-bff57c44dc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce36f344-338c-4a12-be79-4320d9b6ed42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>PO number is 22 character max.</value>
      <webElementGuid>b7126f51-ea83-45ab-a1a8-7ce78e0ca1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>7766f823-8611-4554-acc8-4b223340daf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please provide a valid PO Number.</value>
      <webElementGuid>9f206b70-e894-4e9f-be83-514e1c58e77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerPoNumber</value>
      <webElementGuid>b73920f8-f75c-4bc6-af95-16aac60fe171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>93c8d59f-6725-45aa-beb5-cc095bbc87cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerPoNumber</value>
      <webElementGuid>e6c3b527-96c6-4517-b0f4-3509ab257af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer PO #_</value>
      <webElementGuid>aaf734a4-2005-4024-89e0-e1436e8f0602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2128cc7d0c3fbb23edbdb942e3141ae6</value>
      <webElementGuid>6c211c52-2841-4f32-94f0-535abba052bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'CustomerPoNumber']</value>
      <webElementGuid>d42dd86a-6a12-4785-a27e-a105c561174a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'CustomerPoNumber']</value>
      <webElementGuid>f7c76ea3-3bfa-40f6-9254-5cd4d2629654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CustomerPoNumber' and @name = 'CustomerPoNumber' and (text() = 'Customer PO #_' or . = 'Customer PO #_')]</value>
      <webElementGuid>8c90e324-beb1-4031-8303-d187fa88f07e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
