<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkout-btn</name>
   <tag></tag>
   <elementGuidId>785b3968-050e-4fcc-a185-419bdc1a7d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'checkout-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b93b915e-a61e-414d-8b48-991e87cfddd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { disabled: !hasShippingMethod() || isDisable() || checkoutDisable() || hasInvalidDnr() }</value>
      <webElementGuid>d1e0ffaa-0bfe-4768-8f70-48108acdc6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>58848ff4-3c45-4199-9ff0-9b25537afc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>782a8e57-97d7-4067-b2e2-6f71274fbca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34b1d1ce-ed62-4bea-8ef6-429cd7cb41cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cartService.checkout()</value>
      <webElementGuid>8ec6c9fa-36c8-476d-b430-844d2ea35275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn checkout</value>
      <webElementGuid>2bfe1360-9de4-4aa4-8c12-f79aed2bc106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>6a0fd2d4-9339-4429-927a-aed78532ab82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>7b77683b-6698-4ccb-ba4f-fdfa1cade800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1953c70763ee508726ffb0f720002ac8</value>
      <webElementGuid>f98c5d1c-852b-4772-8e65-fc962f24d264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'checkout-btn']</value>
      <webElementGuid>a2051067-9c6f-4bb6-b936-c9febdb3c888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'checkout-btn']</value>
      <webElementGuid>fc52bac9-19e2-4a7f-9844-5f4bfe035006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkout-btn' and @type = 'button' and (text() = 'checkout-btn' or . = 'checkout-btn')]</value>
      <webElementGuid>20beb464-bba6-4e50-ab83-8f3f0ddd390b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
