<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkout-btn</name>
   <tag></tag>
   <elementGuidId>d7422680-828b-4e03-8774-c1952775ddfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'checkout-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b23b604a-7424-4a8d-a803-ae3d48c3e34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { disabled: !hasShippingMethod() || isDisable() || checkoutDisable() || hasInvalidDnr() }</value>
      <webElementGuid>0e7eea0c-ebe4-468a-877f-8ae75e84fca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>b13a7d5a-7049-44be-b52e-2e2036e3c709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>04f0b16a-2ac9-4fba-9287-9c2a426f83a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1be97edb-494f-4f45-b622-0e92d94f6191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cartService.checkout()</value>
      <webElementGuid>7add322f-5827-4a36-8de5-e9f4feb8cf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn checkout</value>
      <webElementGuid>72d4f40e-5fa4-47b4-8de1-68418b76d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>6ef2253e-7623-402e-8811-42c1656c5fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkout-btn</value>
      <webElementGuid>d3bd7a73-3531-4de6-8dbf-57debeefb6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1953c70763ee508726ffb0f720002ac8</value>
      <webElementGuid>8ae412af-4ca6-4094-aa1f-0aba4721bbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'checkout-btn']</value>
      <webElementGuid>a517009d-d205-4b9a-b1ee-d78724ffa20c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'checkout-btn']</value>
      <webElementGuid>97cddf57-748c-492f-9e60-3177806be111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkout-btn' and @type = 'button' and (text() = 'checkout-btn' or . = 'checkout-btn')]</value>
      <webElementGuid>02299160-b61b-455b-b1e1-770b5fa0514b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
