<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delivery</name>
   <tag></tag>
   <elementGuidId>483d453d-0bce-4759-8541-14b2afc5ff85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-e2e-testing-id=&quot;cart-delivery&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-e2e-testing-id = 'cart-delivery']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf6140b3-ff67-40cd-852c-8fb0adc005c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e-testing-id</name>
      <type>Main</type>
      <value>cart-delivery</value>
      <webElementGuid>f801c76d-b191-424c-8d10-6e8d62bce2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-radio</value>
      <webElementGuid>300448a6-b3d2-429c-bb82-69d7cc401bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delivery</value>
      <webElementGuid>c8f86a2a-4531-4a26-8a86-6165b060fffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-511dfff11b759f1a714201a86d5bc977</value>
      <webElementGuid>6af9eadb-ef2e-4591-aa8d-1644bbc93285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-e2e-testing-id = 'cart-delivery']</value>
      <webElementGuid>d603f198-14a0-4912-9c5c-6ee90474c0f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-e2e-testing-id = 'cart-delivery']</value>
      <webElementGuid>5394496c-6ec6-4e5f-8e4d-96657d458e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Delivery' or . = 'Delivery')]</value>
      <webElementGuid>1c439d09-ba22-4e95-9892-1f1e2fd51733</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
